CREATE TABLE `proofguard_attestations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`attestationId` varchar(64) NOT NULL,
	`executionId` int,
	`stepId` int,
	`agentId` varchar(128) NOT NULL,
	`agentLabel` varchar(255),
	`cqsScore` int NOT NULL,
	`riskTier` enum('low','medium','high','critical') NOT NULL,
	`status` enum('APPROVED','BLOCKED','REQUIRES_HITL','REJECTED') NOT NULL,
	`reason` text NOT NULL,
	`flagged` boolean NOT NULL DEFAULT false,
	`guardrailsTriggered` json,
	`executionSuccess` boolean,
	`executionCompletedAt` timestamp,
	`resultSummary` text,
	`hitlDecision` enum('pending','approved','rejected'),
	`hitlDecidedBy` varchar(255),
	`hitlDecidedAt` timestamp,
	`hitlReason` text,
	`proofHash` varchar(128),
	`attestedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `proofguard_attestations_id` PRIMARY KEY(`id`),
	CONSTRAINT `proofguard_attestations_attestationId_unique` UNIQUE(`attestationId`)
);
