"""
Generative UI — Phase 3 Agentic Workspace
===========================================

Turns agent output into structured UI component descriptors that the React
dashboard dynamically renders. This is the bridge between the Python agent
and the frontend component registry.

Two transport modes, both supported:

  1. Native SSE event (preferred when streaming through Phase2Executor):
     The Python side emits a dedicated `ui_component` SSE event with the
     payload. The frontend registers an EventSource listener on the
     `ui_component` event name and dispatches to the component registry.

  2. In-text delimiter (fallback for plain-text streams):
     Agents that can only return text (e.g. an LLM streaming completion
     without structured output mode) embed markers in the response:

         __GUI_PAYLOAD__{"type":"ui_component",...}__GUI_PAYLOAD_END__

     Phase2Executor scans agent_result payloads for these markers and
     re-emits them as `ui_component` SSE events.

Component schema (validated by UIComponentPayload):
    {
        "type": "ui_component",
        "component": "AnalyticsChart",   // must be in frontend registry
        "props": {
            "title": "...",
            "type": "bar",
            "data": [{"name": "...", "value": 123}, ...],
            "alertText": "..."
        },
        "id": "optional-stable-id",      // for React key and deduplication
        "source_agent": "dynexecutiv",   // for attribution on the frontend
        "timestamp": "2026-04-11T17:30:00Z"
    }

Adding a new component:
    1. Add the name to UI_COMPONENTS below (self-documenting enum)
    2. Add a matching React component in dashboard/src/components/generative/
    3. Register it in dashboard/src/lib/componentRegistry.ts
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from typing import Any, Dict, Iterable, List, Optional, Tuple


# ── Component registry (must stay in sync with the frontend) ───────────────


UI_COMPONENTS = frozenset(
    {
        "AnalyticsChart",     # Bar / line / pie chart with optional alert text
        "AlertBanner",        # Dismissable alert with severity + action button
        "KPICard",            # Single big-number KPI with delta + sparkline
        "MetricsGrid",        # Grid of KPICards
        "ProgressTracker",    # Multi-step progress (e.g., pipeline stage status)
        "ActionList",         # Checklist of recommended actions
        "HITLApprovalCard",   # Human-in-the-loop approve/reject prompt
        "DailyCommandCenter", # Dynexis FounderOS pomodoro sprint board
    }
)


# ── Delimiter markers ──────────────────────────────────────────────────────


GUI_PAYLOAD_START = "__GUI_PAYLOAD__"
GUI_PAYLOAD_END = "__GUI_PAYLOAD_END__"
_MARKER_RE = re.compile(
    re.escape(GUI_PAYLOAD_START) + r"(?P<json>.*?)" + re.escape(GUI_PAYLOAD_END),
    re.DOTALL,
)


# ── Payload dataclass ──────────────────────────────────────────────────────


@dataclass
class UIComponentPayload:
    """
    Structured description of a UI widget the agent wants to render.

    Fields:
        component: Frontend component name (must be in UI_COMPONENTS).
        props: Dict of props passed directly to the React component.
        id: Stable identifier for React keying and deduplication. Auto-generated
            if not provided.
        source_agent: Agent name for attribution (shown in the UI as
            "Generated by <agent>").
        timestamp: ISO-8601 UTC. Auto-filled.
        type: Always "ui_component" — the tag the frontend dispatches on.
    """

    component: str
    props: Dict[str, Any]
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    source_agent: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    type: str = "ui_component"

    def __post_init__(self) -> None:
        if self.component not in UI_COMPONENTS:
            # Not a hard error — allow agents to experiment with new component
            # names as long as they get added to the frontend registry too.
            import logging

            logging.getLogger("launchops.generative_ui").warning(
                "Unknown UI component %r (not in UI_COMPONENTS registry). "
                "The frontend will log a warning and render a fallback.",
                self.component,
            )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), default=str)

    def to_marker(self) -> str:
        """Wrap the payload in the delimited in-text marker format."""
        return f"{GUI_PAYLOAD_START}{self.to_json()}{GUI_PAYLOAD_END}"


# ── Builder shortcuts ──────────────────────────────────────────────────────


def ui_payload(
    component: str,
    props: Dict[str, Any],
    source_agent: Optional[str] = None,
    payload_id: Optional[str] = None,
) -> UIComponentPayload:
    """Concise constructor for agents."""
    return UIComponentPayload(
        component=component,
        props=props,
        source_agent=source_agent,
        id=payload_id or str(uuid.uuid4()),
    )


def analytics_chart(
    title: str,
    data: List[Dict[str, Any]],
    chart_type: str = "bar",
    alert_text: Optional[str] = None,
    source_agent: Optional[str] = None,
) -> UIComponentPayload:
    """Build an AnalyticsChart payload (matching the DynExecutiv example)."""
    props: Dict[str, Any] = {
        "title": title,
        "type": chart_type,
        "data": data,
    }
    if alert_text:
        props["alertText"] = alert_text
    return ui_payload("AnalyticsChart", props, source_agent=source_agent)


def kpi_card(
    label: str,
    value: Any,
    delta: Optional[float] = None,
    delta_label: Optional[str] = None,
    sparkline: Optional[List[float]] = None,
    tone: str = "neutral",  # neutral | positive | negative | warning
    source_agent: Optional[str] = None,
) -> UIComponentPayload:
    """Single big-number KPI card."""
    props: Dict[str, Any] = {"label": label, "value": value, "tone": tone}
    if delta is not None:
        props["delta"] = delta
    if delta_label:
        props["deltaLabel"] = delta_label
    if sparkline:
        props["sparkline"] = sparkline
    return ui_payload("KPICard", props, source_agent=source_agent)


def alert_banner(
    severity: str,  # info | warning | error | success
    title: str,
    message: str,
    action_label: Optional[str] = None,
    action_url: Optional[str] = None,
    source_agent: Optional[str] = None,
) -> UIComponentPayload:
    """Dismissable alert with optional call-to-action button."""
    props: Dict[str, Any] = {
        "severity": severity,
        "title": title,
        "message": message,
    }
    if action_label:
        props["actionLabel"] = action_label
    if action_url:
        props["actionUrl"] = action_url
    return ui_payload("AlertBanner", props, source_agent=source_agent)


def action_list(
    title: str,
    items: List[Dict[str, Any]],
    source_agent: Optional[str] = None,
) -> UIComponentPayload:
    """
    Checklist of recommended actions. Each item should be a dict with:
        {label, description?, completed?, priority?}
    """
    return ui_payload(
        "ActionList",
        {"title": title, "items": items},
        source_agent=source_agent,
    )


def hitl_approval_card(
    attestation_id: str,
    agent: str,
    stage: str,
    plan_summary: str,
    cqs_score: Optional[int] = None,
) -> UIComponentPayload:
    """Prompt the operator to approve or reject a ProofGuard-paused action."""
    props = {
        "attestationId": attestation_id,
        "agent": agent,
        "stage": stage,
        "planSummary": plan_summary,
    }
    if cqs_score is not None:
        props["cqsScore"] = cqs_score
    return ui_payload("HITLApprovalCard", props, source_agent="proofguard")


# ── Extraction helpers ─────────────────────────────────────────────────────


def extract_ui_payloads(value: Any) -> Tuple[List[Dict[str, Any]], Any]:
    """
    Walk an arbitrary agent result and pull out any Generative UI payloads.

    Returns:
        (payloads, cleaned_value)
            payloads       — list of payload dicts (type="ui_component")
            cleaned_value  — the original structure with markers stripped
                             from any strings (for tidier logging/storage)

    Recognizes TWO shapes:
      1. A top-level dict or sub-dict with {"type": "ui_component", ...}
      2. A string containing __GUI_PAYLOAD__...__GUI_PAYLOAD_END__ markers
      3. A dict with a top-level "ui_payloads" list
    """
    payloads: List[Dict[str, Any]] = []

    def _walk(v: Any) -> Any:
        # Strings: scan for delimited markers
        if isinstance(v, str):
            found = list(_MARKER_RE.finditer(v))
            if not found:
                return v
            cleaned = v
            for m in found:
                try:
                    payload = json.loads(m.group("json"))
                    if isinstance(payload, dict) and payload.get("type") == "ui_component":
                        payloads.append(payload)
                except json.JSONDecodeError:
                    continue
                cleaned = cleaned.replace(m.group(0), "")
            return cleaned.strip() or None

        # Dicts: check for native payload shape, then recurse
        if isinstance(v, dict):
            # Case A: a single ui_component payload at this level
            if v.get("type") == "ui_component" and "component" in v:
                payloads.append(v)
                return None

            # Case B: a list of payloads under "ui_payloads"
            ui_list = v.get("ui_payloads")
            if isinstance(ui_list, list):
                for item in ui_list:
                    if isinstance(item, dict) and item.get("type") == "ui_component":
                        payloads.append(item)

            # Recurse into remaining keys
            return {k: _walk(val) for k, val in v.items() if k != "ui_payloads"}

        # Lists: recurse
        if isinstance(v, list):
            cleaned_list: List[Any] = []
            for item in v:
                walked = _walk(item)
                if walked is not None:
                    cleaned_list.append(walked)
            return cleaned_list

        return v

    cleaned = _walk(value)
    return payloads, cleaned


def emit_ui_payloads_from_result(result: Any) -> Iterable[Dict[str, Any]]:
    """Convenience: yield payload dicts from an agent result in order."""
    payloads, _ = extract_ui_payloads(result)
    for p in payloads:
        yield p
