/**
 * GenerativeUIRenderer
 * --------------------
 * Takes a component name + props (from an agent's ui_component payload) and
 * renders the matching React component from the registry. Shows a graceful
 * fallback if the name is unknown so a new Python agent component doesn't
 * take down the dashboard.
 *
 * Usage:
 *   <GenerativeUIRenderer componentName="AnalyticsChart" props={...} />
 *
 * Or pass a whole payload:
 *   <GenerativeUIRenderer payload={uiPayload} />
 */

import { AlertCircle } from 'lucide-react'
import { lookupComponent, type UIComponentPayload } from '../../lib/componentRegistry'

interface RendererProps {
  componentName?: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  props?: Record<string, any>
  payload?: UIComponentPayload
  showAttribution?: boolean
}

export default function GenerativeUIRenderer({
  componentName,
  props,
  payload,
  showAttribution = false,
}: RendererProps) {
  const name = componentName ?? payload?.component
  const componentProps = props ?? payload?.props ?? {}
  const sourceAgent = payload?.source_agent

  if (!name) {
    return (
      <FallbackCard reason="Generative UI payload missing component name" />
    )
  }

  const Component = lookupComponent(name)

  if (!Component) {
    return (
      <FallbackCard
        reason={`Unknown component: "${name}". Register it in componentRegistry.ts.`}
      />
    )
  }

  return (
    <div>
      <Component {...componentProps} />
      {showAttribution && sourceAgent && (
        <div className="text-[10px] text-gray-600 mt-1 text-right font-mono">
          generated by {sourceAgent}
        </div>
      )}
    </div>
  )
}

function FallbackCard({ reason }: { reason: string }) {
  return (
    <div className="flex items-start gap-2 p-3 bg-red-950/30 border border-red-900/50 rounded-lg text-red-300 text-sm">
      <AlertCircle size={14} className="shrink-0 mt-0.5" />
      <span>{reason}</span>
    </div>
  )
}
