"""
Gnoscenti Atlas Engine - Analytics Agent
Deploys Matomo for privacy-friendly, self-hosted web analytics.
Also generates analytics instrumentation code for the product.
"""
from __future__ import annotations
from typing import Any, Dict, List
from agents.base import BaseAgent

COMPOSE_SNIPPET = """\
  matomo:
    image: matomo:latest
    container_name: atlas_matomo
    restart: unless-stopped
    environment:
      - MATOMO_DATABASE_HOST=matomo_db
      - MATOMO_DATABASE_DBNAME=matomo
      - MATOMO_DATABASE_USERNAME=matomo
      - MATOMO_DATABASE_PASSWORD={db_password}
    volumes:
      - ./data/matomo:/var/www/html
    ports:
      - "{port}:80"
    networks:
      - atlas_network
    depends_on:
      - matomo_db

  matomo_db:
    image: mariadb:10.11
    container_name: atlas_matomo_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD={db_root_password}
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=matomo
      - MYSQL_PASSWORD={db_password}
    volumes:
      - ./data/matomo_db:/var/lib/mysql
    networks:
      - atlas_network
"""

TRACKING_CODE_TEMPLATE = """\
<!-- Matomo Analytics — Generated by Gnoscenti Atlas Engine -->
<script>
  var _paq = window._paq = window._paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {{
    var u="{matomo_url}/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '{site_id}']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  }})();
</script>
<!-- End Matomo Analytics -->
"""

KEY_EVENTS = [
    "signup_started",
    "signup_completed",
    "trial_started",
    "subscription_created",
    "subscription_cancelled",
    "feature_used",
    "upgrade_clicked",
    "checkout_started",
    "checkout_completed",
    "support_ticket_created",
]


class AnalyticsAgent(BaseAgent):
    def __init__(self, llm_client=None, config=None):
        super().__init__("Analytics", llm_client, config)

    def analyze(self, context: Dict[str, Any]) -> Dict[str, Any]:
        self.log_info("Analyzing analytics requirements...")
        domain = context.get("domain", "localhost")
        return {
            "port": self.config.ports.get("matomo", 8083),
            "domain": domain,
            "key_events": KEY_EVENTS,
            "features": [
                "Privacy-friendly (GDPR compliant)",
                "No data sharing with third parties",
                "Real-time visitor tracking",
                "Goal and conversion tracking",
                "Funnel analysis",
                "Heatmaps and session recordings",
                "E-commerce tracking",
                "Custom dimensions and variables",
                "API access",
            ],
            "instrumentation_gaps": self._detect_gaps(context),
        }

    def execute(self, task: Dict[str, Any]) -> Dict[str, Any]:
        task_type = task.get("type", "deploy_matomo")
        analysis = task.get("analysis", self.analyze(task))

        if task_type == "deploy_matomo":
            db_password = self.vault.get("db_password", namespace="matomo") or self.vault.generate_password(24)
            db_root_password = self.vault.get("db_root_password", namespace="matomo") or self.vault.generate_password(24)
            self.vault.set_service_credentials("matomo", {
                "db_password": db_password,
                "db_root_password": db_root_password,
            })
            snippet = COMPOSE_SNIPPET.format(
                db_password=db_password,
                db_root_password=db_root_password,
                port=analysis["port"],
            )
            matomo_url = f"http://localhost:{analysis['port']}"
            tracking_code = TRACKING_CODE_TEMPLATE.format(
                matomo_url=matomo_url,
                site_id="1",
            )
            return self.success(
                f"Matomo configured on port {analysis['port']}",
                compose_snippet=snippet,
                tracking_code=tracking_code,
                key_events=KEY_EVENTS,
                admin_url=matomo_url,
            )
        elif task_type == "generate_tracking_code":
            matomo_url = task.get("matomo_url", f"http://localhost:{self.config.ports.get('matomo', 8083)}")
            site_id = task.get("site_id", "1")
            return self.success(
                "Tracking code generated",
                tracking_code=TRACKING_CODE_TEMPLATE.format(matomo_url=matomo_url, site_id=site_id),
                key_events=KEY_EVENTS,
            )
        return self.failure(f"Unknown task type: {task.get('type')}")

    def _detect_gaps(self, context: Dict) -> List[str]:
        gaps = []
        stack = context.get("stack", [])
        stack_lower = " ".join(stack).lower() if stack else ""
        if "analytics" not in stack_lower and "matomo" not in stack_lower and "ga4" not in stack_lower:
            gaps.append("No analytics provider detected in stack")
        if "stripe" in stack_lower and "conversion" not in stack_lower:
            gaps.append("Stripe detected but no conversion tracking configured")
        return gaps
